/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sveinn' at '10/27/15 11:12 PM' with Gradle 2.8
 *
 * @author sveinn, @date 10/27/15 11:12 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
